
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC
    username: postgres
    password: ivqcd4ig
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  tomcat:
    max-swallow-size: 1MB
  error:
    whitelabel:
      enabled: false